import 'package:cloud_firestore/cloud_firestore.dart';
import 'period_model.dart'; // Make sure this path points to your PeriodSlotModel

class DraftTimetableModel {
  final String? id; // Nullable because it's generated by Firestore after saving
  final String teacherId;
  final String timetableName;
  final String status; // 'layout' (empty grid) or 'timetable' (partially filled)
  final DateTime createdDate;
  final Map<String, String> dayTypes; // e.g. {'Monday': 'Working Day'}
  final Map<String, List<PeriodSlotModel>> scheduleData; // The raw grid data

  const DraftTimetableModel({
    this.id,
    required this.teacherId,
    required this.timetableName,
    required this.status,
    required this.createdDate,
    required this.dayTypes,
    required this.scheduleData,
  });

  DraftTimetableModel copyWith({
    String? id,
    String? teacherId,
    String? timetableName,
    String? status,
    DateTime? createdDate,
    Map<String, String>? dayTypes,
    Map<String, List<PeriodSlotModel>>? scheduleData,
  }) {
    return DraftTimetableModel(
      id: id ?? this.id,
      teacherId: teacherId ?? this.teacherId,
      timetableName: timetableName ?? this.timetableName,
      status: status ?? this.status,
      createdDate: createdDate ?? this.createdDate,
      dayTypes: dayTypes ?? this.dayTypes,
      scheduleData: scheduleData ?? this.scheduleData,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'teacherId': teacherId,
      'timetableName': timetableName,
      'status': status,
      'createdDate': Timestamp.fromDate(createdDate),
      'dayTypes': dayTypes,
      // Map the nested lists of PeriodSlotModels into JSON lists
      'scheduleData': scheduleData.map(
            (key, value) => MapEntry(key, value.map((slot) => slot.toMap()).toList()),
      ),
    };
  }

  factory DraftTimetableModel.fromMap(Map<String, dynamic> map, String docId) {
    return DraftTimetableModel(
      id: docId,
      teacherId: map['teacherId'] ?? '',
      timetableName: map['timetableName'] ?? 'Untitled Draft',
      status: map['status'] ?? 'layout',
      createdDate: map['createdDate'] != null
          ? (map['createdDate'] as Timestamp).toDate()
          : DateTime.now(),
      dayTypes: Map<String, String>.from(map['dayTypes'] ?? {}),
      // Safely parse the nested lists back into PeriodSlotModels
      scheduleData: (map['scheduleData'] as Map<String, dynamic>?)?.map(
            (key, value) => MapEntry(
          key,
          (value as List<dynamic>).map((e) => PeriodSlotModel.fromMap(e as Map<String, dynamic>)).toList(),
        ),
      ) ?? {},
    );
  }
}