// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8PreVfAE7JbKlXUGB4ejZTDQJ8CxYDNg',
    appId: '1:458728614797:web:ea469d09bcf5e94355ebc4',
    messagingSenderId: '458728614797',
    projectId: 'scholo-c927b',
    authDomain: 'scholo-c927b.firebaseapp.com',
    storageBucket: 'scholo-c927b.firebasestorage.app',
    measurementId: 'G-TQQK6Q7QY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBkdzKrE_xrHYirTJeuU5h1WU39bbrEKA',
    appId: '1:458728614797:android:0836428db290cbf455ebc4',
    messagingSenderId: '458728614797',
    projectId: 'scholo-c927b',
    storageBucket: 'scholo-c927b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmYVPTxctJUhy4IOABMOSQgsLy8_7wFCM',
    appId: '1:458728614797:ios:625d786f8ce088fc55ebc4',
    messagingSenderId: '458728614797',
    projectId: 'scholo-c927b',
    storageBucket: 'scholo-c927b.firebasestorage.app',
    iosBundleId: 'com.example.scholoAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8PreVfAE7JbKlXUGB4ejZTDQJ8CxYDNg',
    appId: '1:458728614797:web:da2056e1a34723d455ebc4',
    messagingSenderId: '458728614797',
    projectId: 'scholo-c927b',
    authDomain: 'scholo-c927b.firebaseapp.com',
    storageBucket: 'scholo-c927b.firebasestorage.app',
    measurementId: 'G-JRT2B2YHH3',
  );

}