// File generated by FlutterFire CLI (Template for Testing)
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Testing Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // REPLACE THESE PLACEHOLDERS WITH YOUR TESTING PROJECT CREDENTIALS
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDJOXQRixmA_xeWVWRImFYCr-5VQqTbxOM",
    appId: "1:8163441506:web:0199d380e09c4fd9ba8a3b",
    messagingSenderId: "8163441506",
    projectId: "scholo-testing",
    authDomain: "scholo-testing.firebaseapp.com",
    storageBucket: "scholo-testing.firebasestorage.app",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDJOXQRixmA_xeWVWRImFYCr-5VQqTbxOM",
    appId: "1:8163441506:web:0199d380e09c4fd9ba8a3b",
    messagingSenderId: "8163441506",
    projectId: "scholo-testing",
    storageBucket: "scholo-testing.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDJOXQRixmA_xeWVWRImFYCr-5VQqTbxOM",
    appId: "1:8163441506:web:0199d380e09c4fd9ba8a3b",
    messagingSenderId: "8163441506",
    projectId: "scholo-testing",
    storageBucket: "scholo-testing.firebasestorage.app",
    iosBundleId: 'com.example.scholoAdmin.test',
  );
}
